# Generated by Django 2.1.13 on 2019-11-27 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PairKeyReq',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=100)),
                ('purpose', models.CharField(max_length=100, null=True)),
                ('email', models.CharField(max_length=100)),
                ('keytype', models.CharField(max_length=100)),
                ('keysize', models.CharField(max_length=100)),
                ('passphrase', models.CharField(max_length=100)),
                ('privkey', models.TextField(null=True)),
                ('pubkey', models.TextField(null=True)),
                ('datehistory', models.DateTimeField()),
                ('expires', models.DateTimeField()),
            ],
            options={
                'db_table': 'kunci',
                'managed': True,
            },
        ),
    ]
